# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build_and_publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build
      - name: Publish with Gradle
        env:
          GPG_SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: publish -Pgpr.key="${{ secrets.GITHUB_TOKEN }}" -Pgpr.user="${{ github.repository_owner }}" -Possrh.username="${{ secrets.OSSRH_USERNAME }}" -Possrh.password="${{ secrets.OSSRH_PASSWORD }}" -Psigning.password="${{ secrets.SIGNING_PASSWORD }}" -Psigning.key="${{ secrets.SIGNING_KEY }}"
